In [1]:
import numpy as np
import jax.numpy as jnp

In [2]:
DATASET = "cifar10"  # or "mnist"

In [3]:
if DATASET == "mnist":
    from mnist_config import (
        d_in, d_out, seed, N, X_train, Y_train, X_test, Y_test, 
        tau, n_steps, lr_in, lr_out, q, batch_size, 
        last_particle_single_source, eval_every, ACTIVATION, num_repetitions, LOOP_SEED,
        BASE_SETTING_STR
        )
elif DATASET == "cifar10":
    from cifar10_config import (
        d_in, d_out, seed, N, X_train, Y_train, X_test, Y_test, 
        tau, n_steps, lr_in, lr_out, q, batch_size, 
        last_particle_single_source, eval_every, ACTIVATION, num_repetitions, LOOP_SEED,
        BASE_SETTING_STR
    )

/home/maass/pvc/dropout_and_ram_2026/.venv/lib/python3.12/site-packages/torchvision/datasets/cifar.py:83: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  entry = pickle.load(f, encoding="latin1")

(50000, 3072) (50000, 10) (10000, 3072) (10000, 10)

In [4]:
D= 10 if DATASET == "mnist" else 50

In [5]:
configurations = [   
    # (10,2,2),
    #     (10,2,4),
    #     (10,4,2),
    # (10,4,4),
    # (10,4,8),
    #     (10,8,4),
    #     (10,8,8),
    #     (10,8,16),
    #     (10,16,8),
    #     (10,16,16),
    #     (10,16,32),
    #     (10,32,16),
    #     (10,32,32),
    #     (10,32,64),
    #     (10,64,32),
    # (D,64,64),
    # (D,64,128),
    # (D,64,256),
    # (D,64,512),
    # (D,128,64),
    # (D,128,128),
    # (D,128,256),
    # (D,128,512),
    # (D,256,64),
    #(D,256,128),
    #(D,256,256),
    #(D,256,512),
    (D,512,64),
    (D,512,128),
    (D,512,256),
    (D,512,512),
    # Add more as needed
]

print("Configurations to load:", configurations)

Configurations to load: [(50, 512, 64), (50, 512, 128), (50, 512, 256), (50, 512, 512)]

In [6]:
import gc
import jax
from src.utils import compute_train_h_out

def compute_delta_u(params_noisy, params_ref):
    U_noisy = params_noisy.U  # (L, M, D), keep as jax array
    U_ref = params_ref.U
    # # Compute Delta_U: max_l sqrt(1/M * sum_j ||U_noisy[l,j,:] - U_ref[l,j,:]||_2^2)
    # delta_u_per_layer = []
    # for l in range(U_noisy.shape[0]):
    #     diff = U_noisy[l, :, :] - U_ref[l, :, :]  # (M, D)
    #     rms = jnp.sqrt(jnp.mean(jnp.mean(diff**2, axis=1)))  # RMS over particles
    #     delta_u_per_layer.append(rms)
    # return float(jnp.mean(delta_u_per_layer))
    diff = U_noisy - U_ref                      # (L, M, D)
    rms_per_layer = jnp.sqrt(jnp.mean(jnp.mean(diff**2, axis=2), axis=1))  # matches original code exactly  # (L,)
    delta_u = jnp.mean(rms_per_layer)
    return float(delta_u)  # only scalar leaves the device


def compute_delta_v(params_noisy, params_ref):
    V_noisy = params_noisy.V  # (L, M, D)
    V_ref = params_ref.V
    # Compute Delta_V: max_l sqrt(1/M * sum_j ||V_noisy[l,j,:] - V_ref[l,j,:]||_2^2)
    # delta_v_per_layer = []
    # for l in range(V_noisy.shape[0]):
    #     diff = V_noisy[l, :, :] - V_ref[l, :, :]  # (M, D)
    #     rms = np.sqrt(np.mean(np.mean(diff**2, axis=1)))
    #     delta_v_per_layer.append(rms)
    # delta_v = np.mean(delta_v_per_layer)

    diff = V_noisy - V_ref
    rms_per_layer = jnp.sqrt(jnp.mean(jnp.mean(diff**2, axis=2), axis=1))  # (L,)
    delta_v = jnp.mean(rms_per_layer)

    return float(delta_v)

# def compute_delta_h(history_noisy, history_ref):
#     h_noisy = history_noisy['test_h']  # keep as jax array
#     h_ref = history_ref['test_h']
#     diff_h = h_noisy - h_ref
#     l2_norms_h = jnp.linalg.norm(diff_h, axis=2)
#     return float(jnp.mean(l2_norms_h))  # only this scalar leaves the device
def compute_delta_h(params_noisy, params_ref, X_test, activation):
    h_noisy, _ = compute_train_h_out(params_noisy, X_test, activation)
    h_ref, _ = compute_train_h_out(params_ref, X_test, activation)

    diff_h = h_noisy - h_ref
    l2_norms_h = jnp.linalg.norm(diff_h, axis=2)
    delta_h = float(jnp.mean(l2_norms_h))

    del h_noisy, h_ref, diff_h, l2_norms_h
    return delta_h

def compute_parameter_distance_metrics(final_params_noisy, final_params_ref, X_test, activation, variant_name=None):
    """
    Compute parameter distance metrics between noisy (DO/RaM) and reference (GD) solutions.
    
    Args:
        final_params_noisy: params from dropout/ram training (dict of lists or single params)
        final_params_ref: reference params (e.g., from GD)
        X_test: test data
        activation: activation function
        variant_name: variant identifier for printing
    
    Returns:
        Dictionary with Delta_U, Delta_V, Delta_h metrics (averaged over repetitions if applicable)
    """
    
    # Handle both single runs and multiple repetitions
    if isinstance(final_params_noisy, list):
        num_reps = len(final_params_noisy)
        is_repeated = True
    else:
        num_reps = 1
        final_params_noisy = [final_params_noisy]
        histories_noisy = [histories_noisy]
        is_repeated = False
    
    all_delta_u = []
    all_delta_v = []
    all_delta_h = []
    
    for rep_idx in range(num_reps):
        params_noisy = final_params_noisy[rep_idx]
        params_ref = final_params_ref[rep_idx]
        #history_noisy = histories_noisy[rep_idx]
        #history_ref = histories_ref[rep_idx]
        
        #U_noisy = np.asarray(params_noisy.U)  # (L, M, D)
        #V_noisy = np.asarray(params_noisy.V)  # (L, M, D)
        
        #U_ref = np.asarray(params_ref.U)      # (L, M, D)
        #V_ref = np.asarray(params_ref.V)      # (L, M, D)
        
        
        delta_u = compute_delta_u(params_noisy, params_ref)
        delta_v = compute_delta_v(params_noisy, params_ref)
        
        # Compute Delta_h: max_{i,l} ||h_noisy[l,i,:] - h_ref[l,i,:]||_2
        delta_h = compute_delta_h(params_noisy, params_ref, X_test, activation)
        
        all_delta_u.append(delta_u)
        all_delta_v.append(delta_v)
        all_delta_h.append(delta_h)

        del params_noisy, params_ref
        gc.collect()
        jax.clear_caches()
    
    # Average over repetitions if applicable
    result = {
        'Delta_U': np.mean(all_delta_u),
        'Delta_V': np.mean(all_delta_v),
        'Delta_h': np.mean(all_delta_h),
    }
    
    if is_repeated:
        result['Delta_U_std'] = np.std(all_delta_u)
        result['Delta_V_std'] = np.std(all_delta_v)
        result['Delta_h_std'] = np.std(all_delta_h)
    
    return result

In [7]:
import pickle
from src.utils import add_train_h_out

results_multi = []

for D_config, L_config, M_config in configurations:
    setting_str = f'L{L_config}_M{M_config}_D{D_config}' + BASE_SETTING_STR
    
    print(f"\nLoading configuration: D={D_config}, L={L_config}, M={M_config}")
    try:
        with open(f'data/{DATASET}/final_params_do_{setting_str}.pkl', 'rb') as f:
            final_params_do_config = pickle.load(f)
        with open(f'data/{DATASET}/histories_do_{setting_str}.pkl', 'rb') as f:
            histories_do_config = pickle.load(f)
        with open(f'data/{DATASET}/final_params_ram_{setting_str}.pkl', 'rb') as f:
            final_params_ram_config = pickle.load(f)
        with open(f'data/{DATASET}/histories_ram_{setting_str}.pkl', 'rb') as f:
            histories_ram_config = pickle.load(f)
        #with open(f'data/{DATASET}/final_params_gd_{setting_str}.pkl', 'rb') as f:
        #    final_params_gd_config = pickle.load(f)
        #with open(f'data/{DATASET}/histories_gd_{setting_str}.pkl', 'rb') as f:
        #    histories_gd_config = pickle.load(f)
        
               
        #histories_do = add_train_h_out(final_params_do_config, histories_do_config, X_test, ACTIVATION)
        #histories_ram = add_train_h_out(final_params_ram_config, histories_ram_config, X_test, ACTIVATION)
        #histories_gd = add_train_h_out(final_params_gd_config, histories_gd_config, X_test, ACTIVATION)

        # Compute metrics for each variant
        for variant in ['full_unit_dropout', 'stochastic_depth', 'single_source_M']:
            metrics_do_vs_ram = compute_parameter_distance_metrics(
                final_params_do_config[variant],
                final_params_ram_config[variant],
                #histories_do_config[variant],
                #histories_ram_config[variant],
                X_test,
                ACTIVATION,
                variant_name=f"dropout:{variant}"
            )
            
            results_multi.append({
                'D': D_config,
                'L': L_config,
                'M': M_config,
                'M*L': L_config * M_config,
                'variant': variant,
                'method': 'dropout',
                'Delta_U': metrics_do_vs_ram['Delta_U'],
                'Delta_U_std': metrics_do_vs_ram.get('Delta_U_std', 0),
                'Delta_V': metrics_do_vs_ram['Delta_V'],
                'Delta_V_std': metrics_do_vs_ram.get('Delta_V_std', 0),
                'Delta_h': metrics_do_vs_ram['Delta_h'],
                'Delta_h_std': metrics_do_vs_ram.get('Delta_h_std', 0),
            })
            
            print(f"  {variant}:")
            print(f"    DO: ΔU = {metrics_do_vs_ram['Delta_U']:.4e}, ΔV = {metrics_do_vs_ram['Delta_V']:.4e}")

    except FileNotFoundError as e:
        print(f"  WARNING: Could not load {setting_str}: {e}")

# Convert to DataFrame for easier plotting
import pandas as pd
df_results = pd.DataFrame(results_multi)
print("\nResults summary:")
print(df_results)

Loading configuration: D=50, L=512, M=64

  full_unit_dropout:
    DO: ΔU = 2.6497e-02, ΔV = 2.2755e-02
  stochastic_depth:
    DO: ΔU = 2.7723e-02, ΔV = 2.3963e-02
  single_source_M:
    DO: ΔU = 3.4104e-02, ΔV = 3.0577e-02

Loading configuration: D=50, L=512, M=128
  full_unit_dropout:
    DO: ΔU = 1.7490e-02, ΔV = 1.5303e-02
  stochastic_depth:
    DO: ΔU = 1.9397e-02, ΔV = 1.6975e-02
  single_source_M:
    DO: ΔU = 2.2839e-02, ΔV = 2.0046e-02

Loading configuration: D=50, L=512, M=256
  full_unit_dropout:
    DO: ΔU = 1.0354e-02, ΔV = 8.9952e-03
  stochastic_depth:
    DO: ΔU = 1.2622e-02, ΔV = 1.0923e-02
  single_source_M:
    DO: ΔU = 1.3668e-02, ΔV = 1.1845e-02

Loading configuration: D=50, L=512, M=512
  full_unit_dropout:
    DO: ΔU = 7.2953e-03, ΔV = 6.6487e-03
  stochastic_depth:
    DO: ΔU = 1.1694e-02, ΔV = 1.0163e-02
  single_source_M:
    DO: ΔU = 1.2238e-02, ΔV = 1.1639e-02

Results summary:
     D    L    M     M*L            variant   method   Delta_U  Delta_U_std  \
0   50  512   64   32768  full_unit_dropout  dropout  0.026497     0.002076
1   50  512   64   32768   stochastic_depth  dropout  0.027723     0.002059
2   50  512   64   32768    single_source_M  dropout  0.034104     0.002872
3   50  512  128   65536  full_unit_dropout  dropout  0.017490     0.002332
4   50  512  128   65536   stochastic_depth  dropout  0.019397     0.001978
5   50  512  128   65536    single_source_M  dropout  0.022839     0.003230
6   50  512  256  131072  full_unit_dropout  dropout  0.010354     0.000984
7   50  512  256  131072   stochastic_depth  dropout  0.012622     0.000885
8   50  512  256  131072    single_source_M  dropout  0.013668     0.001365
9   50  512  512  262144  full_unit_dropout  dropout  0.007295     0.000677
10  50  512  512  262144   stochastic_depth  dropout  0.011694     0.000851
11  50  512  512  262144    single_source_M  dropout  0.012238     0.001291

     Delta_V  Delta_V_std   Delta_h  Delta_h_std
0   0.022755     0.002356  0.029273     0.008212
1   0.023963     0.002268  0.034946     0.007023
2   0.030577     0.003191  0.048893     0.009709
3   0.015303     0.002777  0.021259     0.004503
4   0.016975     0.002357  0.022608     0.004204
5   0.020046     0.003321  0.031268     0.009081
6   0.008995     0.001120  0.013333     0.004803
7   0.010923     0.000930  0.018548     0.006760
8   0.011845     0.001323  0.018625     0.006845
9   0.006649     0.000819  0.010549     0.002112
10  0.010163     0.000793  0.016545     0.005949
11  0.011639     0.001396  0.024929     0.006992

In [8]:
df_results

,D,L,M,M*L,variant,method,Delta_U,Delta_U_std,Delta_V,Delta_V_std,Delta_h,Delta_h_std
0,50,512,64,32768,full_unit_dropout,dropout,0.026497,0.002076,0.022755,0.002356,0.029273,0.008212
1,50,512,64,32768,stochastic_depth,dropout,0.027723,0.002059,0.023963,0.002268,0.034946,0.007023
2,50,512,64,32768,single_source_M,dropout,0.034104,0.002872,0.030577,0.003191,0.048893,0.009709
3,50,512,128,65536,full_unit_dropout,dropout,0.017490,0.002332,0.015303,0.002777,0.021259,0.004503
4,50,512,128,65536,stochastic_depth,dropout,0.019397,0.001978,0.016975,0.002357,0.022608,0.004204
5,50,512,128,65536,single_source_M,dropout,0.022839,0.003230,0.020046,0.003321,0.031268,0.009081
6,50,512,256,131072,full_unit_dropout,dropout,0.010354,0.000984,0.008995,0.001120,0.013333,0.004803
7,50,512,256,131072,stochastic_depth,dropout,0.012622,0.000885,0.010923,0.000930,0.018548,0.006760
8,50,512,256,131072,single_source_M,dropout,0.013668,0.001365,0.011845,0.001323,0.018625,0.006845
9,50,512,512,262144,full_unit_dropout,dropout,0.007295,0.000677,0.006649,0.000819,0.010549,0.002112
10,50,512,512,262144,stochastic_depth,dropout,0.011694,0.000851,0.010163,0.000793,0.016545,0.005949
11,50,512,512,262144,single_source_M,dropout,0.012238,0.001291,0.011639,0.001396,0.024929,0.006992

In [9]:
df_results.to_csv(f"plots/{DATASET}/data_rms_nsteps50_pt5.csv", index=False)

In [10]:
import pandas as pd

In [11]:
df_results1 = pd.read_csv(f"plots/{DATASET}/data_rms_nsteps50.csv")
#df_results2 = pd.read_csv(f"plots/{DATASET}/data_rms_nsteps50_pt2.csv")
#df_results3 = pd.read_csv(f"plots/{DATASET}/data_rms_nsteps50_pt3.csv")
#df_results4 = pd.read_csv(f"plots/{DATASET}/data_rms_nsteps50_pt4.csv")
df_results5 = pd.read_csv(f"plots/{DATASET}/data_rms_nsteps50_pt5.csv")

In [12]:
df_results1

,D,L,M,M*L,variant,method,Delta_U,Delta_U_std,Delta_V,Delta_V_std,Delta_h,Delta_h_std
0,50,64,64,4096,full_unit_dropout,dropout,0.045938,0.001604,0.039966,0.001414,0.063364,0.005258
1,50,64,64,4096,stochastic_depth,dropout,0.050811,0.001799,0.044343,0.002236,0.069612,0.009313
2,50,64,64,4096,single_source_M,dropout,0.050640,0.002688,0.044322,0.002835,0.071649,0.010582
3,50,64,128,8192,full_unit_dropout,dropout,0.030477,0.000486,0.027039,0.000458,0.037012,0.004230
4,50,64,128,8192,stochastic_depth,dropout,0.042570,0.003199,0.038824,0.003713,0.060299,0.018074
5,50,64,128,8192,single_source_M,dropout,0.037074,0.004625,0.033352,0.004889,0.054482,0.014268
6,50,64,256,16384,full_unit_dropout,dropout,0.020341,0.001188,0.017666,0.001347,0.024743,0.002925
7,50,64,256,16384,stochastic_depth,dropout,0.029991,0.002554,0.026421,0.001893,0.039448,0.006023
8,50,64,256,16384,single_source_M,dropout,0.023009,0.002021,0.020193,0.002059,0.030201,0.006329
9,50,64,512,32768,full_unit_dropout,dropout,0.013455,0.000146,0.011771,0.000149,0.016110,0.001269
10,50,64,512,32768,stochastic_depth,dropout,0.027076,0.001231,0.023556,0.001647,0.035232,0.004436
11,50,64,512,32768,single_source_M,dropout,0.016052,0.001376,0.014168,0.001262,0.026752,0.009445
12,50,128,64,8192,full_unit_dropout,dropout,0.043149,0.002686,0.040521,0.003107,0.059171,0.012608
13,50,128,64,8192,stochastic_depth,dropout,0.045310,0.002036,0.041325,0.002253,0.063645,0.009894
14,50,128,64,8192,single_source_M,dropout,0.049412,0.004253,0.045261,0.004714,0.070267,0.016029
15,50,128,128,16384,full_unit_dropout,dropout,0.029296,0.001876,0.025362,0.001900,0.031205,0.003345
16,50,128,128,16384,stochastic_depth,dropout,0.036818,0.004348,0.032611,0.004669,0.054668,0.022753
17,50,128,128,16384,single_source_M,dropout,0.037283,0.005023,0.033123,0.005135,0.058381,0.017683
18,50,128,256,32768,full_unit_dropout,dropout,0.015056,0.000699,0.013140,0.000724,0.018400,0.002562
19,50,128,256,32768,stochastic_depth,dropout,0.022064,0.002215,0.019105,0.001975,0.032084,0.004524
20,50,128,256,32768,single_source_M,dropout,0.018335,0.002724,0.015996,0.002532,0.023608,0.004780
21,50,128,512,65536,full_unit_dropout,dropout,0.010184,0.000138,0.008713,0.000061,0.012012,0.000675
22,50,128,512,65536,stochastic_depth,dropout,0.020726,0.001977,0.017796,0.001820,0.027375,0.009909
23,50,128,512,65536,single_source_M,dropout,0.013807,0.001212,0.012137,0.001248,0.021796,0.010196
24,50,256,64,16384,full_unit_dropout,dropout,0.028285,0.001511,0.024362,0.001615,0.037371,0.004947
25,50,256,64,16384,stochastic_depth,dropout,0.031265,0.001731,0.027263,0.002124,0.046234,0.005369
26,50,256,64,16384,single_source_M,dropout,0.034665,0.003268,0.030476,0.003119,0.046702,0.007642
27,50,256,128,32768,full_unit_dropout,dropout,0.017662,0.000243,0.015450,0.000278,0.021391,0.002391
28,50,256,128,32768,stochastic_depth,dropout,0.021749,0.001482,0.019224,0.001460,0.027421,0.005775
29,50,256,128,32768,single_source_M,dropout,0.022757,0.001819,0.020182,0.001831,0.033886,0.007237
30,50,256,256,65536,full_unit_dropout,dropout,0.012721,0.000255,0.010924,0.000283,0.013616,0.000745
31,50,256,256,65536,stochastic_depth,dropout,0.016701,0.001710,0.014059,0.001366,0.020274,0.006945
32,50,256,256,65536,single_source_M,dropout,0.015458,0.001171,0.013288,0.001035,0.020079,0.005396
33,50,256,512,131072,full_unit_dropout,dropout,0.007342,0.000162,0.006215,0.000177,0.008985,0.000477
34,50,256,512,131072,stochastic_depth,dropout,0.014664,0.001760,0.012405,0.001561,0.023599,0.006904
35,50,256,512,131072,single_source_M,dropout,0.011337,0.002013,0.009975,0.002025,0.020330,0.008640

In [13]:
df_results5

,D,L,M,M*L,variant,method,Delta_U,Delta_U_std,Delta_V,Delta_V_std,Delta_h,Delta_h_std
0,50,512,64,32768,full_unit_dropout,dropout,0.026497,0.002076,0.022755,0.002356,0.029273,0.008212
1,50,512,64,32768,stochastic_depth,dropout,0.027723,0.002059,0.023963,0.002268,0.034946,0.007023
2,50,512,64,32768,single_source_M,dropout,0.034104,0.002872,0.030577,0.003191,0.048893,0.009709
3,50,512,128,65536,full_unit_dropout,dropout,0.017490,0.002332,0.015303,0.002777,0.021259,0.004503
4,50,512,128,65536,stochastic_depth,dropout,0.019397,0.001978,0.016975,0.002357,0.022608,0.004204
5,50,512,128,65536,single_source_M,dropout,0.022839,0.003230,0.020046,0.003321,0.031268,0.009081
6,50,512,256,131072,full_unit_dropout,dropout,0.010354,0.000984,0.008995,0.001120,0.013333,0.004803
7,50,512,256,131072,stochastic_depth,dropout,0.012622,0.000885,0.010923,0.000930,0.018548,0.006760
8,50,512,256,131072,single_source_M,dropout,0.013668,0.001365,0.011845,0.001323,0.018625,0.006845
9,50,512,512,262144,full_unit_dropout,dropout,0.007295,0.000677,0.006649,0.000819,0.010549,0.002112
10,50,512,512,262144,stochastic_depth,dropout,0.011694,0.000851,0.010163,0.000793,0.016545,0.005949
11,50,512,512,262144,single_source_M,dropout,0.012238,0.001291,0.011639,0.001396,0.024929,0.006992

In [14]:
df_results = pd.concat([df_results1, df_results5], ignore_index=True)

In [15]:
df_results

,D,L,M,M*L,variant,method,Delta_U,Delta_U_std,Delta_V,Delta_V_std,Delta_h,Delta_h_std
0,50,64,64,4096,full_unit_dropout,dropout,0.045938,0.001604,0.039966,0.001414,0.063364,0.005258
1,50,64,64,4096,stochastic_depth,dropout,0.050811,0.001799,0.044343,0.002236,0.069612,0.009313
2,50,64,64,4096,single_source_M,dropout,0.050640,0.002688,0.044322,0.002835,0.071649,0.010582
3,50,64,128,8192,full_unit_dropout,dropout,0.030477,0.000486,0.027039,0.000458,0.037012,0.004230
4,50,64,128,8192,stochastic_depth,dropout,0.042570,0.003199,0.038824,0.003713,0.060299,0.018074
5,50,64,128,8192,single_source_M,dropout,0.037074,0.004625,0.033352,0.004889,0.054482,0.014268
6,50,64,256,16384,full_unit_dropout,dropout,0.020341,0.001188,0.017666,0.001347,0.024743,0.002925
7,50,64,256,16384,stochastic_depth,dropout,0.029991,0.002554,0.026421,0.001893,0.039448,0.006023
8,50,64,256,16384,single_source_M,dropout,0.023009,0.002021,0.020193,0.002059,0.030201,0.006329
9,50,64,512,32768,full_unit_dropout,dropout,0.013455,0.000146,0.011771,0.000149,0.016110,0.001269
10,50,64,512,32768,stochastic_depth,dropout,0.027076,0.001231,0.023556,0.001647,0.035232,0.004436
11,50,64,512,32768,single_source_M,dropout,0.016052,0.001376,0.014168,0.001262,0.026752,0.009445
12,50,128,64,8192,full_unit_dropout,dropout,0.043149,0.002686,0.040521,0.003107,0.059171,0.012608
13,50,128,64,8192,stochastic_depth,dropout,0.045310,0.002036,0.041325,0.002253,0.063645,0.009894
14,50,128,64,8192,single_source_M,dropout,0.049412,0.004253,0.045261,0.004714,0.070267,0.016029
15,50,128,128,16384,full_unit_dropout,dropout,0.029296,0.001876,0.025362,0.001900,0.031205,0.003345
16,50,128,128,16384,stochastic_depth,dropout,0.036818,0.004348,0.032611,0.004669,0.054668,0.022753
17,50,128,128,16384,single_source_M,dropout,0.037283,0.005023,0.033123,0.005135,0.058381,0.017683
18,50,128,256,32768,full_unit_dropout,dropout,0.015056,0.000699,0.013140,0.000724,0.018400,0.002562
19,50,128,256,32768,stochastic_depth,dropout,0.022064,0.002215,0.019105,0.001975,0.032084,0.004524
20,50,128,256,32768,single_source_M,dropout,0.018335,0.002724,0.015996,0.002532,0.023608,0.004780
21,50,128,512,65536,full_unit_dropout,dropout,0.010184,0.000138,0.008713,0.000061,0.012012,0.000675
22,50,128,512,65536,stochastic_depth,dropout,0.020726,0.001977,0.017796,0.001820,0.027375,0.009909
23,50,128,512,65536,single_source_M,dropout,0.013807,0.001212,0.012137,0.001248,0.021796,0.010196
24,50,256,64,16384,full_unit_dropout,dropout,0.028285,0.001511,0.024362,0.001615,0.037371,0.004947
25,50,256,64,16384,stochastic_depth,dropout,0.031265,0.001731,0.027263,0.002124,0.046234,0.005369
26,50,256,64,16384,single_source_M,dropout,0.034665,0.003268,0.030476,0.003119,0.046702,0.007642
27,50,256,128,32768,full_unit_dropout,dropout,0.017662,0.000243,0.015450,0.000278,0.021391,0.002391
28,50,256,128,32768,stochastic_depth,dropout,0.021749,0.001482,0.019224,0.001460,0.027421,0.005775
29,50,256,128,32768,single_source_M,dropout,0.022757,0.001819,0.020182,0.001831,0.033886,0.007237
30,50,256,256,65536,full_unit_dropout,dropout,0.012721,0.000255,0.010924,0.000283,0.013616,0.000745
31,50,256,256,65536,stochastic_depth,dropout,0.016701,0.001710,0.014059,0.001366,0.020274,0.006945
32,50,256,256,65536,single_source_M,dropout,0.015458,0.001171,0.013288,0.001035,0.020079,0.005396
33,50,256,512,131072,full_unit_dropout,dropout,0.007342,0.000162,0.006215,0.000177,0.008985,0.000477
34,50,256,512,131072,stochastic_depth,dropout,0.014664,0.001760,0.012405,0.001561,0.023599,0.006904
35,50,256,512,131072,single_source_M,dropout,0.011337,0.002013,0.009975,0.002025,0.020330,0.008640
36,50,512,64,32768,full_unit_dropout,dropout,0.026497,0.002076,0.022755,0.002356,0.029273,0.008212
37,50,512,64,32768,stochastic_depth,dropout,0.027723,0.002059,0.023963,0.002268,0.034946,0.007023
38,50,512,64,32768,single_source_M,dropout,0.034104,0.002872,0.030577,0.003191,0.048893,0.009709
39,50,512,128,65536,full_unit_dropout,dropout,0.017490,0.002332,0.015303,0.002777,0.021259,0.004503
40,50,512,128,65536,stochastic_depth,dropout,0.019397,0.001978,0.016975,0.002357,0.022608,0.004204
41,50,512,128,65536,single_source_M,dropout,0.022839,0.003230,0.020046,0.003321,0.031268,0.009081
42,50,512,256,131072,full_unit_dropout,dropout,0.010354,0.000984,0.008995,0.001120,0.013333,0.004803
43,50,512,256,131072,stochastic_depth,dropout,0.012622,0.000885,0.010923,0.000930,0.018548,0.006760
44,50,512,256,131072,single_source_M,dropout,0.013668,0.001365,0.011845,0.001323,0.018625,0.006845
45,50,512,512,262144,full_unit_dropout,dropout,0.007295,0.000677,0.006649,0.000819,0.010549,0.002112
46,50,512,512,262144,stochastic_depth,dropout,0.011694,0.000851,0.010163,0.000793,0.016545,0.005949
47,50,512,512,262144,single_source_M,dropout,0.012238,0.001291,0.011639,0.001396,0.024929,0.006992

In [16]:
df_results.to_csv(f"plots/{DATASET}/data_rms_nsteps50.csv", index=False)